---
name: Lint Code Base

#
# Documentation: https://github.com/github/super-linter
# Linter configurations are in .github/linters/
#

on: [push]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: dec5e/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          OUTPUT_DETAILS: detailed
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
